### Get all alerts
GET {{users.url}}/alerts

> {%
    const alert = response.body[0];

    // convert format "dd-MM-yyyy" to "yyyy-MM-dd"
    function formatDate(date) {
        const parts = date.split("-");
        return `${parts[2]}-${parts[1]}-${parts[0]}`;
    }

    client.global.set("alertId", alert.id);
    client.global.set("alertFromDate", formatDate(alert.from));
    client.global.set("alertToDate", formatDate(alert.to));
    client.global.set("alertProductId", alert.productId);
    client.global.set("userId", alert.userId);
    %}

### Get alert by ID {{alertId}}
GET {{users.url}}/alerts/{{alertId}}

### Get alerts by product and date
GET {{users.url}}/alerts/byProductAndDate?productId={{alertProductId}}&availableOnDate={{alertFromDate}}

### Get alerts by user and interval
GET {{users.url}}/alerts/byUserAndInterval?userId={{userId}}&fromDate={{alertFromDate}}&toDate={{alertToDate}}

### Create alert
POST {{users.url}}/alerts
Content-Type: application/json

{
  "productId": {{alertProductId}},
  "userId": {{userId}},
  "from": "2025-10-23",
  "to": "2025-10-24"
}
