### Get all users
# @name getAllUsers
GET {{users.url}}/users
Accept: application/json

> {%
    client.global.set("userId", response.body[0].id)
    client.global.set("userEmail", response.body[0].email)
%}

### Get user by ID
GET {{users.url}}/users/{{userId}}
Accept: application/json

### Get user by email
GET {{users.url}}/users/byEmail/{{userEmail}}

### Users to alert
GET {{users.url}}/users/toAlert
    ?productId=1
    &availableOnDate=2025-05-01T14:00:00Z

### Create user
POST {{users.url}}/users
Content-Type: application/json

{
    "fullName": "Pau Colomé",
    "email": "pcolomed@uoc.edu",
    "password": "12345678",
    "phoneNumber": "+34666666666"
}
